### ISSUE TITLE
Can't install Aplication

### ISSUE THREAD

**Issue by AlekseyRazuvay** [sauljabin/kaskade#19]
**Describe the bug**
Can't install on my mac m1.

**To Reproduce**
1. pip install kaskade
**Error**:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting kaskade
  Using cached kaskade-1.1.8-py3-none-any.whl (38 kB)
Collecting PyYAML<6.0.0,>=5.4.1 (from kaskade)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/razuvajaleksej/Library/Python/3.10/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/razuvajaleksej/Library/Python/3.10/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/razuvajaleksej/Library/Python/3.10/lib/python/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/hw/nvzq554j1fs0cgkjk1wcts_m0000gq/T/pip-build-env-vziuwn4_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Desktop (please complete the following information):**
 - OS: 14.1.2
 - Version [23B92]
 - Python 3.10.5

**Comment by sauljabin** [comment]
Hello @AlekseyRazuvay would you mind to check the new version? I have released the v2
