### ISSUE TITLE
Can't install because of PyYaml < 6.0

### ISSUE THREAD

**Issue by harry19023** [sauljabin/kaskade#20]
**Describe the bug**
```
  - Downgrading pyyaml (6.0.1 -> 5.4.1): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  running egg_info
  writing lib3/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib3/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/poetry/1.8.2/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/homebrew/Cellar/poetry/1.8.2/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/homebrew/Cellar/poetry/1.8.2/libexec/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 271, in <module>
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
      super().run_command(command)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
      self.find_sources()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
      mm.run()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 550, in run
      self.add_defaults()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
      sdist.add_defaults(self)
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
      super().add_defaults()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
      self._add_defaults_ext()
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
    File "<string>", line 201, in get_source_files
    File "/var/folders/bh/v_m6z59d1vj7lz4g3xkjsz200000gn/T/tmp2ijnmwhk/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources

**Comment by harry19023** [comment]
https://github.com/yaml/pyyaml/issues/736

**Comment by sauljabin** [comment]
Hi @harry19023 the new version (v2) is out, please check it out and let me know your feedback.

- Now it does not need a yaml

Thanks for using it and helping me to improve it
